### ISSUE TITLE
Cannot read properties of undefined (reading 'color')

### ISSUE THREAD

**Issue by mandytwig** [Pioreactor/pioreactorui#147]
I have received this error a few times when I am currently running 24 pioreactors simultaneously. Thanks!

Something went wrong with the PioreactorUI!
Don't worry. It's our fault. Here's what you can do:
Looks like there's a bug in the UI. See the below for error information. We would appreciate it if you create an issue in [Github](https://github.com/Pioreactor/pioreactorui/issues) for us, with the information below.

URL: http://lead1.local/overview
Cannot read properties of undefined (reading 'color')

**Comment by CamDavidsonPilon** [comment]
Hi @mandytwig, 

We noticed a few other users with large clusters experiencing this same problem. We believe we fixed in the version 24.9.19 or above. Can you try upgrading your cluster? (The version 24.9.19 is a large upgrade, so make sure there are no experiments running).https://forum.pioreactor.com/t/new-pioreactor-release-24-9-19/462?u=camdavidsonpilon

**Comment by mandytwig** [comment]
We have upgraded our software. I haven't received the error since. Thanks!
